version: 1.5.{build}
image:
- Visual Studio 2019
- Visual Studio 2017
- Visual Studio 2015
- Visual Studio 2013
configuration:
- Debug
- Release
#platform:
#- Win32
#- x64
before_build:
- cmd: cmake -H. -B./build
build:
  verbosity: normal
